import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import DownloadCV from '../../components/DownloadCV';

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['contact', 'common'])),
    },
  };
}

const Contact = () => {
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>{t('contact:SEOtitle')}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="contact-container">
        <header>
          <h1>{t('contact:title')}</h1>

          <DownloadCV value={t('common:downloadCVTitle')} />

          <p>{t('contact:desc')}</p>
        </header>
        <main className="mainContainer">
          <form className="bg-yellow-400 dark:bg-neutral-800 grid p-8">
            <label htmlFor="name">Fullt navn</label>
            <input type="text" name="name" id="name" />

            <label htmlFor="mail">E-post adresse</label>
            <input type="mail" name="mail" id="mail" />

            <label htmlFor="message">Melding</label>
            <textarea name="message" id="message"></textarea>

            <button
              className="bg-blue-600 text-white font-heading font-bold tracking-wider py-5"
              type="submit"
            >
              Send melding
            </button>
          </form>
        </main>
      </div>
    </>
  );
};

export default Contact;
