import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import Link from 'next/link';
import { FiExternalLink } from 'react-icons/fi';
import DownloadCV from '../../components/DownloadCV';

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['home', 'common'])),
    },
  };
}

const About = (props) => {
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>Om meg - Jostein Tollefsrud</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <h1>Om meg</h1>

        <DownloadCV value={t('common:downloadCVTitle')} />
        <Link href="/">
          <a className="text-blue-600">
            GitHub profil <FiExternalLink className="inline mb-1" />
          </a>
        </Link>
      </header>
      <main className="mainContainer">
        <p>
          Lorem Ipsum is simply dummy text of the printing and typesetting
          industry. Lorem Ipsum has been the industrys standard dummy text ever
          since the 1500s, when an unknown printer took a galley of type and
          scrambled it to make a type specimen book. It has survived not only
          five centuries, but also the leap into electronic typesetting,
          remaining essentially unchanged. It was popularised in the 1960s with
          the release of Letraset sheets containing Lorem Ipsum passages, and
          more recently with desktop publishing software like Aldus PageMaker
          including versions of Lorem Ipsum.
        </p>
      </main>
    </>
  );
};

export default About;
