import Head from 'next/head';
import Link from 'next/link';

const ProjectPage = () => {
  return (
    <>
      <Head>
        <title>Prosjektside</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
};

export default ProjectPage;
